### ISSUE TITLE
Images are not optimized

### ISSUE THREAD

**Issue by strawberry-choco** [htruong/ezpi4me#3]
The images in `README.md` have rooms for improvements:
* Screenshots of Konsole have huge transparent borders (not sure if intensional or not).
* The bigger images can be optimized to use much less storage (and thus less network bandwidth) without significant loss of quality.
* The image in 'Where is the flash chip?' does not indicate where the chip is. It can be solved by pointing an arrow to it.

I can fix all the aforementioned points if you give me about 24 hours of time. Also please tell me whether the border on the Konsole screenshots are intentional. :)

**Comment by htruong** [comment]
Hello,

- The screenshot was not intentional, I was just using the stock screenshot tool.
- I agree.
- I agree too.

If you could, please help and I'll merge the changes :) Thanks. I don't have an image editor so that's why they were quite rough.

**Comment by strawberry-choco** [comment]
The optimized images are finished. These things have been done:
* Removed transparent borders of Konsole screenshots.
* Converted Konsole screenshots to gifs with color palettes of 32 colors and 128 colors. One of them needs to have 128 colors because it contains gradients and they look awful with less colors. More information about this technique can be found on [wikipedia](https://en.wikipedia.org/wiki/Indexed_color).
* Cut off the top of the chip image because that space is not needed.
* JPGs are now smaller.
* JPGs now are in low quality (10 to 30% quality).

[chip](https://user-images.githubusercontent.com/20382692/36319970-d968bf94-1344-11e8-9af3-39cbbf3fa49a.jpg)
[connection](https://user-images.githubusercontent.com/20382692/36319971-d9a08c1c-1344-11e8-9720-4f81d07d4558.jpg)
[konsole-ime-check](https://user-images.githubusercontent.com/20382692/36319973-d9c570e0-1344-11e8-9bdf-dd9c6c2790fa.gif)
[konsole-pi](https://user-images.githubusercontent.com/20382692/36319974-d9e7b286-1344-11e8-8106-ccf5bf809fec.gif)

**Comment by htruong** [comment]
Thank you, that's a smart way to handle attachments and not having to rely on imgur. I have merged the pull request.
